# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(b79b0c4e-3053-4a3f-a956-d1989ee9698f)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      git tag --sort=v:refname | Select-Object -Last 1      
      $virtualApplications = (az webapp config show --name "dev-gitworkflow" -g "dev-app-service" --query "virtualApplications") | ConvertFrom-Json
      $jsonContent = [PSCustomObject]@{
        "physicalPath" = "site\wwwroot\v3"
        "preloadEnabled" = $false
        "virtualDirectories" = $null
        "virtualPath" = "/v3" 
      }  
      $virtualApplications += $jsonContent
      $virtualApplications = $virtualApplications | ConvertTo-Json
      $jsonFile = '"{{\"virtualApplications\": {0} }}"' -f $virtualApplications.Replace('"','\"')